<?PHP

/**
 * Path Defines
 */
define("ACIES_ROOT", $_SERVER['DOCUMENT_ROOT']);
define("ACIES_LIB", ACIES_ROOT."/lib");
define("ACIES_CLASSES_DIR", ACIES_LIB."/classes");
define("ACIES_APP_CLASSES_DIR", ACIES_CLASSES_DIR."/application");
define("ACIES_DB_CLASSES_DIR", ACIES_CLASSES_DIR."/database");
define("ACIES_ADDONS_DIR", ACIES_LIB."/addons");
define("ACIES_CRON", ACIES_LIB."/cron");
define("ACIES_CSS", "/lib/css");
define("ACIES_JS", "/lib/js");
define("ACIES_IMAGES", "/lib/images");
define("ACIES_TEMPLATES", ACIES_LIB."/templates");
define("ACIES_LANG", ACIES_LIB."/lang");
define("ACIES_HTCODE", ACIES_LIB."/htcode");
define("ACIES_HTACCESS", ACIES_LIB."/htaccess");
define("ACIES_WWW", ACIES_ROOT."/www");

?>